apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: "mission2"
spec:
  containers:
  - name: stress
    image: alpine
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache stress-ng
        stress-ng --cpu 4 --cpu-method all
    resources:
      requests:
        cpu: 100m
      limits:
        cpu: 200m